//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.14 at 02:35:24 PM MSK 
//


package ru.kogut.enterprise.ws.users;

import lombok.Setter;
import org.springframework.boot.actuate.health.Health;

import javax.xml.bind.annotation.*;

@Setter
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "result",
})
@XmlRootElement(name = "healthRequest")
public class HealthRequest {

    @XmlElement(required = true)
    protected String result;

}
