//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.14 at 02:35:24 PM MSK 
//


package ru.kogut.enterprise.ws.users;

import ru.kogut.enterprise.ws.users.LoginRequest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.kogut.ws.users package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AllUsersRequest_QNAME = new QName("http://kogut.ru/ws/users", "allUsersRequest");
    private final static QName _HealthRequest_QNAME = new QName("http://kogut.ru/ws/users", "healthRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.kogut.ws.users
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link GetUserByIdRequest }
     * 
     */
    public GetUserByIdRequest createGetUserByIdRequest() {
        return new GetUserByIdRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kogut.ru/ws/users", name = "allUsersRequest")
    public JAXBElement<Object> createAllUsersRequest(Object value) {
        return new JAXBElement<Object>(_AllUsersRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kogut.ru/ws/users", name = "healthRequest")
    public JAXBElement<Object> createHealthRequest(Object value) {
        return new JAXBElement<Object>(_HealthRequest_QNAME, Object.class, null, value);
    }

}
